
language: php

php:
  - 5.5
  - 5.4
  - 5.3

env:
  - DB=sqlite
  - DB=mysql

services:
  - memcached

install:
  - curl -sS https://getcomposer.org/installer | php
  - php composer.phar install --prefer-dist --optimize-autoloader --dev --no-interaction

before_script:
  - ./tests/generate_test_sqlite
  - mysql -e 'create database yapo_test;'
  - mysql -u travis yapo_test < 'tests/test.dump'
  - phpenv config-add my.php.ini
  - mkdir -p build/logs

script:
  - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml tests/YapoTest.php

after_script:
  - ./vendor/bin/coveralls -v