
language: php

php:
  - 5.5
  - 5.4
  - 5.3

env:
  - DB=sqlite
  - DB=mysql

branches:
  only:
    - master

install:
  - curl -sS https://getcomposer.org/installer | php
  - php composer.phar install --dev

before_script:
  - ./tests/generate_test_sqlite
  - mysql -e 'create database yapo_test;'
  - mysql -u travis yapo_test < 'tests/test.dump'

script: ./vendor/bin/phpunit tests/YapoTest.php